story/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls'))
]

story4/urls.py
from django.urls import path, include
from . import views
from .views import all_event, add_event, delete_all, delete_event

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('experience/', views.experience, name='experience'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),

    path('all_event/', views.all_event, name='all_event'),
    path('add_event/', views.add_event, name='add_event'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('delete_event/<int:pk>', views.delete_event, name='delete_event')
]

story4/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from django.utils import timezone

# Create your models here.
class Event(models.Model):
    category = models.CharField(blank=False, max_length=20)
    event_name = models.CharField(blank = False, max_length = 30)
	#event_name = models.CharField(blank=False, max_length=30)
    date_time = models.DateTimeField(blank=False, default=timezone.now)
    location = models.TextField(blank = True, null = True)
	#location = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True, max_length=150)

    def __str__(self):
        return self.event_name
	#def __str__(self):
		#return self.event_name

story4/forms.py
from django import forms
from django.forms import Form
from django.utils import timezone

CATEGORY_CHOICES = [
    ('Academic','Academic'),
    ('Entertainment','Entertainment'),
    ('Family','Family'),
    ('Friends','Friends'),
    ('Organization','Organization'),
    ('Other','Other')
    ]

class Event_Form(forms.Form):

    pos_attrs = {
        'class': 'form-control',
        
    }
    category = forms.CharField(label='Category', required=True, widget=forms.Select(choices=CATEGORY_CHOICES))
    event_name = forms.CharField(label='Name', required=True, max_length=40, widget=forms.TextInput(attrs=pos_attrs))
    date_time = forms.DateTimeField(
                input_formats=['%d/%m/%Y %H:%M'],
                widget=forms.DateTimeInput(attrs={
                'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker1'
                })
                )
    location = forms.CharField(label="Location", required=False)
    notes = forms.CharField(label="Notes", widget=forms.Textarea(attrs=pos_attrs), required=False, max_length=150)

story4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import Event_Form
from .models import Event
from django.contrib import messages

response = {}

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def experience(request):
    return render(request, 'experience.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

def add_event(request):
    if request.method == 'POST':      
   
        # A POST request: Handle Form Upload
        form = Event_Form(request.POST) # Bind data from request.POST into a PostForm
 
        # If data is valid, proceeds to create a new post and redirect the user
        if form.is_valid():
            messages.success(request, 'Event added succesfully!')

            category = form.cleaned_data['category']
            event_name = form.cleaned_data['event_name']
            date_time = form.cleaned_data['date_time']
          
            location = form.cleaned_data['location']
            notes = form.cleaned_data['notes']
            event = Event.objects.create(category=category, 
                                        event_name=event_name, 
                                        date_time=date_time,
                                       
                                        location=location,
                                        notes=notes)
            return redirect('story4:add_event')
    else:

        form = Event_Form()

    return render(request, 'addevent.html', {
        'form': form,
    })

def all_event(request):
    allevents = Event.objects.all()
    context={
    'allevents':allevents
    }
    return render(request, 'allevent.html', context)

def delete_event(request, pk):
    Event.objects.filter(pk=pk).delete()
    allevents = Event.objects.all()
    context = {'allevents':allevents}

    return redirect('story4:all_event')
    

def delete_all(request):
    if request.method == "POST":
        Event.objects.all().delete()
        allevents = Event.objects.all()
        context = {'allevents':allevents}
        
        return redirect('story4:all_event')
    else:
        return redirect('story4:all_event')

story4/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="about" class="container-fluid"><br>
                <p class="tiga">About me.</p>
                <div id="garis"></div>
                <br>
                <p class="empat">
                    Ferenica is a second year student<br>
                    of Universitas Indonesia majored <br>
                    in Computer Science. She was born <br>
                    in Kendari, a small capital in middle <br>
                    part of Indonesia, she is 19 years old <br>
                    and 5'5” tall. Besides that, she is <br>
                    also fueled by her passion for <br>
                    learning about graphic designs.
                </p>
                <div>
                    <img class="rounded-circle" src="{% static 'images/foto3.jpg' %}" alt="at beach">
                </div>
            </div>
        </body>
    </div>
</html>
{% endblock %}

story4/templates/addevent.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="jadwal" class="container-fluid"><br>
                <p class="tiga">Add new event</p>
                <div id="garis"></div>
                <br>

                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <form action="{% url 'story4:add_event' %}" method="POST">
                    {% csrf_token %}
          
                    <div class="form-group">
          
                        {{form.category.label}} <br>
                        {{form.category}} <br>
          
                        {{form.event_name.label}} <br>
                        {{form.event_name}}
          
                        {{form.date_time.label}} <br>
                        <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                          
                          {{ form.date_time }} <br>
                          <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        </div>
                        {{form.location.label}} <br>
                        {{ form.location }} <br>
          
                        {{form.notes.label}} <br>
                        {{ form.notes }}
                    </div>
                    <button type='submit' class="btn btn-secondary">Submit</button>
                    <a href="{% url 'story4:all_event' %}" class="btn btn-secondary">Back to My Events</a>
                </form>
            </div>

            <script>
                $(function () {
                    $("#datetimepicker1").datetimepicker({
                    format: 'DD/MM/YYYY HH:mm',
                    });
                });
            </script>
        </body>
    </div>
</html>   
{% endblock %}       
          

story4/templates/allevent.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="jadwal" class="container-fluid"><br>
                <p class="tiga">My Event.</p>
                <div id="garis"></div>
                <br>
                <table class="table">
                    <thead>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Date/Time</th>
                        <th>Location</th>
                        <th>Notes</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for event in allevents %}
                        <tr class="success">
                            <td> {{event.category}} </td>
                            <td> {{event.event_name}} </td>
                            <td> {{event.date_time}} </td>
                            <td> {{event.location}} </td>
                            <td> {{event.notes}} </td>
                            <td><a href="{% url 'story4:delete_event' pk=event.pk %}" ><button type="button" class="btn btn-icon btn-danger">Delete</button></a></td>
                        </tr>             
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'story4:add_event' %}" class="btn btn-secondary" role="button">Add new event</a>
    
                <form method="POST" action="{% url 'story4:delete_all' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-icon btn-danger">Delete All</button>
                </form>
            </div>
        </body>
    </div>
</html>
{% endblock %}
        

story4/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        {% include "head.html" %}
    </head>

    <body>
        {% include "navbar.html" %}
        {% block content %} {% endblock %}
    </body>
</html>

story4/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="contact" class="container-fluid"><br>
                <p class="tiga">Contact me.</p>
                <div id="garis"></div>
                <br>
                <div class="sembilan">
                    <p>Ferenica Dwi Putri<br>STUDENT</p>
                    <br>
                    <p>Phone : <br>0821-8762-6752</p>
                    <br>
                    <p>Email : <br>ferenicha@gmail.com</p>
                </div>
                <div>
                    <img class="plus" src="{% static 'images/plus.png' %}" alt="ikon plus">
                </div>
                
                <div>
                    <a href="https://twitter.com/ferenichaaa">
                        <img class="twit" src="{% static 'images/twit.png' %}" alt="ikon twitter">
                    </a>
                    <a href="https://www.instagram.com/ferenichaaa/">
                        <img class="insta" src="{% static 'images/insta.png' %}" alt="ikon instagram">
                    </a>
                    <a href="https://www.facebook.com/ferenicadwiputri">
                        <img class="fb" src="{% static 'images/fb.png' %}" alt="ikon facebook">
                    </a>
                    <a href="https://www.linkedin.com/in/ferenica-dwi-56b18b194/">
                        <img class="linkedin" src="{% static 'images/linkedin.png' %}" alt="ikon linkedin">
                    </a>
                </div>
                <div>
                    <p class="sepuluh">Follow me</p>
                </div>
                
            </div>
        </body>
    </div>
</html>
{% endblock %}

story4/templates/experience.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="experience" class="container-fluid"><br>
                <p class="tiga">Experience</p>
                <div id="garis"></div>
                <br>

                <div class="main-timeline">
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content">
                            <span class="date">2017-2018</span>
                            <p class="title"><b>Kelompok Ilmiah Remaja <br> SMA Negeri 1 Kendari</b></p>
                            <p class="description">
                                Secretary    
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content right">
                            <span class="date">2018-present</span>
                            <p class="title"><b>Gabungan Putra-putri<br>Sulawesi Tenggara (Gapura UI)</b></p>
                            <p class="description">
                                Head of Public Relation, Publication and Design Division
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content">
                            <span class="date">2019-present</span>
                            <p class="title"><b>Forum Ukhuwah dan Kajian Islam<br>Fasilkom UI</b></p>
                            <p class="description">
                                Staff of Community Social Department
                            </p>
                        </div>
                    </div>
                 
                    <div class="timeline">
                        <div class="timeline-icon"></div>
                        <div class="timeline-content right">
                            <span class="date">2019-present</span>
                            <p class="title"><b>Dewan Perwakilan Mahasiswa<br>Fasilkom UI</b></p>
                            <p class="description">
                                Staff of Secretary Division
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </div>
</html>
{% endblock %}

story4/templates/form.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<body class="form-body">
    <div class="form-cont">
        <h2>Buat Jadwal</h2>
        <form method="POST" class="form">
            {% csrf_token %}
            <p>Nama Kegiatan:</p>
            {{ form.name }}
            <p>Deskripsi Kegiatan:</p>
            {{ form.desc }}
            <p>Kategori</p>
            {{ form.category }}
            <p>Tempat</p>
            {{ form.location }}
            <p>Waktu & Tanggal</p>
            <p>
                {{ form.date }}
                {{ form.time }}
            </p>
            <div class="full">
                <a href="jadwalku.html"><button type="button" class="button-jadwal delete">Back</button></a>
                <input type="submit" class="button-jadwal" value="Submit" />
            </div>
        </form>
    </div>
</body>
{% endblock %}

story4/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
            </div>

            <div id="gallery" class="container-fluid"><br>
                <p class="tiga">Gallery</p>
                <div id="garis"></div>
                <p id="byMe">Taken by me : )</p>
                <br>
                <img src="{% static 'images/1.jpg' %}" class="byMe">
                <img src="{% static 'images/2.jpg' %}" class="byMe">
                <img src="{% static 'images/3.jpg' %}" class="byMe">
                <img src="{% static 'images/4.jpg' %}" class="byMe">
                <img src="{% static 'images/5.jpg' %}" class="byMe">
                <img src="{% static 'images/6.jpg' %}" class="byMe">
            </div>
        </body>
    </div>
</html>
{% endblock %}

story4/templates/head.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<meta charset="utf-8">
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0' />
<title>myProfile</title>
<link href="https://fonts.googleapis.com/css?family=Boogaloo|Fjalla+One|Grenze|Livvic&display=swap" rel="stylesheet">

story4/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>

<html>
    <div>
        <head>
            {% include 'head.html' %}
        </head>
    </div>

    <div>
        <body style="background-color: #D0CEC5;">
            <div class="container">
                <br>
                <p id="name">Feren.</p>
                <br>
            </div>

            <div id="home" class="container-fluid"><br>
                <div id="aturHome">
                    <p class="satu">Hello, I'm</p>
                    <p class="dua">Ferenica<br>Dwi Putri</p>
                </div>
                <div id="garisHome"></div>
                <br>
                <img class="kanan" src="{% static 'images/foto1.jpg' %}" alt="in front of tree">
            </div>
        </body>
    </div>

</html>
{% endblock %}

story4/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'story4:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'story4:about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'story4:experience' %}">Experience</a>
            <a class="nav-item nav-link" href="{% url 'story4:gallery' %}">Gallery</a>
            <a class="nav-item nav-link" href="{% url 'story4:contact' %}">Contact</a> 
            <a class="nav-item nav-link" href="{% url 'story4:all_event' %}">Event</a> 
        </div>
    </div>  
</nav>